services:
  web-blue:
    build:
      context: .
      dockerfile: ./deploy/dev/django/django.dockerfile
    container_name: web-blue
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./log:/misc/project/job-noti/log:rw
      - ./data:/misc/project/job-noti/data:rw

  web-green:
    build:
      context: .
      dockerfile: ./deploy/dev/django/django.dockerfile
    container_name: web-green
    env_file:
      - .env
    ports:
      - "8002:8000"
    volumes:
      - ./log:/misc/project/job-noti/log:rw
      - ./data:/misc/project/job-noti/data:rw
