# Generated by Django 5.0.4 on 2024-08-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="알림 고유 아이디",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
            },
        ),
        migrations.CreateModel(
            name="NotificationJobNotice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="알림 채용 공고 고유 아이디",
                    ),
                ),
            ],
            options={
                "db_table": "notification_job_notice",
            },
        ),
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="알림 설정 고유 아이디",
                    ),
                ),
                (
                    "send_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="알림 방송 시간"
                    ),
                ),
            ],
            options={
                "db_table": "notification_setting",
            },
        ),
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="알림 유형 고유 아이디",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="이름")),
                (
                    "description",
                    models.CharField(max_length=64, null=True, verbose_name="설명"),
                ),
            ],
            options={
                "db_table": "notification_type",
            },
        ),
    ]
