# Generated by Django 5.0.4 on 2024-08-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("name", models.CharField(max_length=16, verbose_name="이름")),
                (
                    "description",
                    models.CharField(max_length=64, null=True, verbose_name="설명"),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="지역 고유 아이디",
                    ),
                ),
            ],
            options={
                "db_table": "area",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("name", models.CharField(max_length=16, verbose_name="이름")),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="기업 고유 아이디",
                    ),
                ),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="DevOccupation",
            fields=[
                ("name", models.CharField(max_length=16, verbose_name="이름")),
                (
                    "description",
                    models.CharField(max_length=64, null=True, verbose_name="설명"),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="개발 직무 고유 아이디",
                    ),
                ),
            ],
            options={
                "db_table": "dev_occupation",
            },
        ),
        migrations.CreateModel(
            name="ExperienceYear",
            fields=[
                ("name", models.CharField(max_length=16, verbose_name="이름")),
                (
                    "description",
                    models.CharField(max_length=64, null=True, verbose_name="설명"),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="경력 고유 아이디",
                    ),
                ),
            ],
            options={
                "db_table": "experience_year",
            },
        ),
        migrations.CreateModel(
            name="RecruitSite",
            fields=[
                ("name", models.CharField(max_length=16, verbose_name="이름")),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="채용 사이트 고유 아이디",
                    ),
                ),
                ("link", models.CharField(max_length=512, verbose_name="링크")),
            ],
            options={
                "db_table": "recruit_site",
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                ("name", models.CharField(max_length=16, verbose_name="이름")),
                (
                    "description",
                    models.CharField(max_length=64, null=True, verbose_name="설명"),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="기술 스택 고유 아이디",
                    ),
                ),
            ],
            options={
                "db_table": "tech_stack",
            },
        ),
    ]
